package com.mx.uaz.mobileTracking.model;
// Generated 19/07/2017 02:04:06 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Edificiohistorico generated by hbm2java
 */
@Entity
@Table(name = "edificiohistorico")
public class EdificioHistorico implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idEdificioHistorico;
	private String descripcion;
	private double latitud;
	private double longitud;
	private Set<PreferenciaUsuario> preferenciaUsuarios = new HashSet<PreferenciaUsuario>(0);
	private Set<Visita> visitas = new HashSet<Visita>(0);

	public EdificioHistorico() {
	}

	public EdificioHistorico(int idEdificioHistorico, String descripcion, double latitud, double longitud) {
		this.idEdificioHistorico = idEdificioHistorico;
		this.descripcion = descripcion;
		this.latitud = latitud;
		this.longitud = longitud;
	}

	public EdificioHistorico(int idEdificioHistorico, String descripcion, double latitud, double longitud,
			Set<PreferenciaUsuario> preferenciaUsuarios, Set<Visita> visitas) {
		this.idEdificioHistorico = idEdificioHistorico;
		this.descripcion = descripcion;
		this.latitud = latitud;
		this.longitud = longitud;
		this.preferenciaUsuarios = preferenciaUsuarios;
		this.visitas = visitas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idEdificioHistorico", unique = true, nullable = false)
	public int getIdEdificioHistorico() {
		return this.idEdificioHistorico;
	}

	public void setIdEdificioHistorico(int idEdificioHistorico) {
		this.idEdificioHistorico = idEdificioHistorico;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	@Column(name = "descripcion", nullable = false, length = 45)
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "latitud", nullable = false)
	public double getLatitud() {
		return this.latitud;
	}

	public void setLatitud(double latitud) {
		this.latitud = latitud;
	}

	@Column(name = "longitud", nullable = false)
	public double getLongitud() {
		return this.longitud;
	}

	public void setLongitud(double longitud) {
		this.longitud = longitud;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "edificioHistorico")
	public Set<PreferenciaUsuario> getPreferenciaUsuarios() {
		return this.preferenciaUsuarios;
	}

	public void setPreferenciaUsuarios(Set<PreferenciaUsuario> preferenciaUsuarios) {
		this.preferenciaUsuarios = preferenciaUsuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "edificioHistorico")
	public Set<Visita> getVisitas() {
		return this.visitas;
	}

	public void setVisitas(Set<Visita> visitas) {
		this.visitas = visitas;
	}

}
