package com.mx.uaz.mobileTracking.model;
// Generated 19/07/2017 02:04:06 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Preferenciausuario generated by hbm2java
 */
@Entity
@Table(name = "preferenciausuario")
public class PreferenciaUsuario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idPreferenciaUsuario;
	private Usuario usuario;
	private EdificioHistorico edificioHistorico;
	private Boolean like;

	public PreferenciaUsuario() {
	}

	public PreferenciaUsuario(Integer idPreferenciaUsuario, Usuario usuario, EdificioHistorico edificioHistorico,
			Boolean like) {
		this.idPreferenciaUsuario = idPreferenciaUsuario;
		this.usuario = usuario;
		this.edificioHistorico = edificioHistorico;
		this.like = like;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idPreferenciaUsuario", unique = true, nullable = false)
	public Integer getIdPreferenciaUsuario() {
		return this.idPreferenciaUsuario;
	}

	public void setIdPreferenciaUsuario(Integer idPreferenciaUsuario) {
		this.idPreferenciaUsuario = idPreferenciaUsuario;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "edificioHistorico", nullable = false)
	public EdificioHistorico getEdificioHistorico() {
		return this.edificioHistorico;
	}

	public void setEdificioHistorico(EdificioHistorico edificioHistorico) {
		this.edificioHistorico = edificioHistorico;
	}

	@Column(name = "like", nullable = false)
	public Boolean isLike() {
		return this.like;
	}

	public void setLike(Boolean like) {
		this.like = like;
	}

}
