package com.mx.uaz.mobileTracking.model;
// Generated 19/07/2017 02:04:06 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Registrocoordendas generated by hbm2java
 */
@Entity
@Table(name = "registrocoordendas")
public class RegistroCoordendas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idRegistroCoordendas;
	private Usuario usuario;
	private double latitud;
	private double longitud;
	private Date fecha;

	public RegistroCoordendas() {
	}

	public RegistroCoordendas(int idRegistroCoordendas, Usuario usuario, double latitud, double longitud, Date fecha) {
		this.idRegistroCoordendas = idRegistroCoordendas;
		this.usuario = usuario;
		this.latitud = latitud;
		this.longitud = longitud;
		this.fecha = fecha;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idRegistroCoordendas", unique = true, nullable = false)
	public int getIdRegistroCoordendas() {
		return this.idRegistroCoordendas;
	}

	public void setIdRegistroCoordendas(int idRegistroCoordendas) {
		this.idRegistroCoordendas = idRegistroCoordendas;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "latitud", nullable = false)
	public double getLatitud() {
		return this.latitud;
	}

	public void setLatitud(double latitud) {
		this.latitud = latitud;
	}

	@Column(name = "longitud", nullable = false)
	public double getLongitud() {
		return this.longitud;
	}

	public void setLongitud(double longitud) {
		this.longitud = longitud;
	}

	@Column(name = "fecha", nullable = false)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
