package com.mx.uaz.mobileTracking.model;
// Generated 19/07/2017 02:04:06 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario")
public class Usuario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idUsuario;
	private String correo;
	private String password;
	private Set<RegistroCoordendas> registroCoordendases = new HashSet<RegistroCoordendas>(0);
	private Set<Visita> visitas = new HashSet<Visita>(0);
	private Set<PreferenciaUsuario> preferenciaUsuarios = new HashSet<PreferenciaUsuario>(0);

	public Usuario() {
	}

	public Usuario(Integer idUsuario, String password, String correo) {
		this.idUsuario = idUsuario;
		this.password = password;
		this.correo = correo;
	}

	public Usuario(Integer idUsuario, String password, String correo, Set<RegistroCoordendas> registroCoordendases, Set<Visita> visitas,
			Set<PreferenciaUsuario> preferenciaUsuarios) {
		this.idUsuario = idUsuario;
		this.password = password;
		this.correo = correo;
		this.registroCoordendases = registroCoordendases;
		this.visitas = visitas;
		this.preferenciaUsuarios = preferenciaUsuarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idUsuario", unique = true, nullable = false)
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "correo", nullable = false, length = 45)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "password", nullable = false, length = 10)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<RegistroCoordendas> getRegistroCoordendases() {
		return this.registroCoordendases;
	}

	public void setRegistroCoordendases(Set<RegistroCoordendas> registroCoordendases) {
		this.registroCoordendases = registroCoordendases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Visita> getVisitas() {
		return this.visitas;
	}

	public void setVisitas(Set<Visita> visitas) {
		this.visitas = visitas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<PreferenciaUsuario> getPreferenciaUsuarios() {
		return this.preferenciaUsuarios;
	}

	public void setPreferenciaUsuarios(Set<PreferenciaUsuario> preferenciaUsuarios) {
		this.preferenciaUsuarios = preferenciaUsuarios;
	}

}
